/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Places */
        get: operations["list_places_api_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pois
         * @description Ławki i przewijaki z OSM dla warstw mapy (w obszarze demo ok. 1400 ławek).
         */
        get: operations["list_pois_api_pois_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Tryby z ekranu startowego: preferencje trasy i domyślne warstwy mapy.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Geojson
         * @description Ta sama trasa co `POST /routes`, jako GeoJSON FeatureCollection.
         *
         *     Odcinki mają `properties.kind = "segment"` i `index`, trasa bazowa (najkrótsza zwykła)
         *     `kind = "baseline"`. Podsumowanie trasy jest w `properties` kolekcji.
         */
        post: operations["plan_geojson_api_routes_geojson_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description Zgłoszenia miasta, najnowsze pierwsze; opcjonalnie tylko o danym statusie.
         */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        /**
         * Create Report
         * @description Nowe zgłoszenie bariery. Zapisujemy tylko to, co w formularzu - bez IP i danych osobowych.
         */
        post: operations["create_report_api_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Reports
         * @description Potwierdzone zgłoszenia, które teraz wpływają na trasy (#63) - z rodzajem wpływu.
         */
        get: operations["list_active_reports_api_reports_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote On Report
         * @description Inna osoba potwierdza zgłoszenie albo mówi, że problemu już nie ma (#62).
         *
         *     Przewaga 2 głosów jednej strony zmienia status (patrz app/report_votes.py). Jeden głos
         *     na zgłoszenie z urządzenia - kolejny zastępuje poprzedni.
         */
        post: operations["vote_on_report_api_reports__report_id__votes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Report
         * @description Zmiana statusu zgłoszenia (moderacja). TODO(api): uprawnienia moderatora - #37.
         */
        patch: operations["update_report_api_reports__report_id__patch"];
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geocode
         * @description Podpowiedzi adresów, tylko z obszaru miasta (demo_bbox).
         */
        get: operations["geocode_api_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reverse Geocode
         * @description Adres najbliższy punktowi (np. kliknięciu na mapie); null poza obszarem miasta.
         */
        get: operations["reverse_geocode_api_geocode_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Institutions
         * @description Instytucje publiczne z deklaracji dostępności (BIP) wraz z lokalizacją.
         */
        get: operations["list_institutions_api_institutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Wyszukiwarka miejsc w obszarze demo: instytucje, miejsca z OSM, adresy.
         *
         *     Z `lat`/`lon` bliższe wyniki są wyżej, a każdy ma `distance_m`.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Segments
         * @description Odcinki sieci pieszej z atrybutami dostępności jako GeoJSON.
         */
        get: operations["list_segments_api_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Gaps
         * @description Ile i gdzie brakuje danych o dostępności sieci pieszej - tekst do mapy braków (#31).
         */
        get: operations["data_gaps_api_data_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Barriers
         * @description Bariery (schody, krawężniki, strome i nierówne odcinki, zgłoszenia) w obszarze.
         */
        get: operations["list_barriers_api_barriers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * City Stats
         * @description Dashboard miasta: pokrycie danymi, bariery, ranking ulic, zgłoszenia (obszar demo).
         */
        get: operations["city_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessibilityAttribute */
        AccessibilityAttribute: {
            key: components["schemas"]["AttributeKey"];
            /** Value */
            value: boolean | number | string;
            provenance: components["schemas"]["Provenance"];
            /**
             * Confidence
             * @description 0 = nie wiemy, 1 = pewne
             */
            confidence: number;
            /** @default unverified */
            status: components["schemas"]["AttributeStatus"];
            /** Alternatives */
            alternatives?: components["schemas"]["AccessibilityAttribute"][];
        };
        /**
         * ActiveReport
         * @description Potwierdzone zgłoszenie, które teraz wpływa na trasy (#63).
         */
        ActiveReport: {
            /** Id */
            id: string;
            type: components["schemas"]["ReportType"];
            /**
             * Effect
             * @description block - odcinek omijany, penalty - omijany, jeśli jest objazd, warn - tylko ostrzeżenie (winda, wejście, parking)
             * @enum {string}
             */
            effect: "block" | "penalty" | "warn";
            /** Label */
            label: string;
            location: components["schemas"]["LatLon"];
            /**
             * Active Until
             * Format: date-time
             */
            active_until: string;
        };
        /**
         * AttributeKey
         * @description Słownik cech dostępności. Dodajemy nowe klucze tutaj, nie ad hoc w kodzie.
         * @enum {string}
         */
        AttributeKey: "wheelchair" | "step_free_entrance" | "stairs" | "step_count" | "ramp" | "elevator" | "accessible_toilet" | "surface" | "incline_percent" | "kerb_height_cm" | "width_cm" | "tactile_paving" | "blocked" | "accessible_parking" | "changing_table";
        /**
         * AttributeStatus
         * @enum {string}
         */
        AttributeStatus: "verified" | "unverified" | "conflicting" | "outdated";
        /** Barrier */
        Barrier: {
            /**
             * Id
             * @description 'segment:{id}' albo 'report:{id}'
             */
            id: string;
            type: components["schemas"]["BarrierType"];
            /**
             * Description
             * @description Np. 'Schody, 81 stopni; kostka granitowa (bruk)'
             */
            description: string;
            /** Street */
            street?: string | null;
            /** @description Punkt na ikonę (środek odcinka) */
            location: components["schemas"]["LatLon"];
            /**
             * Geometry
             * @description Przebieg odcinka; dla zgłoszenia jeden punkt
             */
            geometry: components["schemas"]["LatLon"][];
            /** Length M */
            length_m?: number | null;
            /**
             * Source
             * @description Nazwa źródła, np. 'osm', 'user_reports'
             */
            source: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Confidence */
            confidence: number;
            /** Last Verified */
            last_verified?: string | null;
            /** @description Tylko dla zgłoszeń użytkowników: status i głosy innych osób */
            report?: components["schemas"]["BarrierReport"] | null;
        };
        /** BarrierCount */
        BarrierCount: {
            type: components["schemas"]["BarrierType"];
            /** Count */
            count: number;
            /** Length M */
            length_m: number;
        };
        /** BarrierList */
        BarrierList: {
            /** Barriers */
            barriers: components["schemas"]["Barrier"][];
            /**
             * Truncated
             * @description True, gdy w bbox jest więcej barier niż limit
             * @default false
             */
            truncated: boolean;
        };
        /**
         * BarrierReport
         * @description Stan zgłoszenia użytkownika pokazanego jako bariera - do głosowania (#62).
         */
        BarrierReport: {
            /** Report Id */
            report_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "confirmed";
            /** Confirmations */
            confirmations: number;
            /** Denials */
            denials: number;
        };
        /**
         * BarrierType
         * @enum {string}
         */
        BarrierType: "stairs" | "kerb" | "steep" | "rough_surface" | "reported";
        /** CityConfig */
        CityConfig: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Timezone */
            timezone: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Demo Bbox */
            demo_bbox?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Center */
            center: [
                number,
                number
            ];
            /**
             * Default Zoom
             * @default 13
             */
            default_zoom: number;
            /** Providers */
            providers?: components["schemas"]["ProviderConfig"][];
            routing?: components["schemas"]["RoutingConfig"];
            /** Pois */
            pois?: {
                [key: string]: unknown;
            };
        };
        /** CityStats */
        CityStats: {
            /** City */
            city: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Network Length M
             * @description Długość sieci pieszej w obszarze demo
             */
            network_length_m: number;
            /** Network Segments */
            network_segments: number;
            /** Coverage */
            coverage: components["schemas"]["Coverage"][];
            /**
             * Gap Length M
             * @description Odcinki bez danych o nawierzchni (jak /api/data-gaps)
             */
            gap_length_m: number;
            /** Gap Share */
            gap_share: number;
            /** Barriers Total */
            barriers_total: number;
            /** Barriers By Type */
            barriers_by_type: components["schemas"]["BarrierCount"][];
            /** Priority Weights */
            priority_weights: {
                [key: string]: number;
            };
            /** Priority Streets */
            priority_streets: components["schemas"]["PriorityStreet"][];
            /**
             * Reports Total
             * @description None = magazyn zgłoszeń niedostępny
             */
            reports_total: number | null;
            /** Reports By Status */
            reports_by_status: components["schemas"]["ReportStatusCount"][];
            /** Reports By Type */
            reports_by_type: components["schemas"]["ReportTypeCount"][];
        };
        /** Coverage */
        Coverage: {
            /**
             * Key
             * @description Cecha odcinka, np. 'surface', 'incline_percent'
             */
            key: string;
            /**
             * Sources
             * @description Skąd pochodzi, np. ['osm'] albo ['nmt_gugik']
             */
            sources: string[];
            /**
             * Length M
             * @description Długość odcinków, które mają tę cechę
             */
            length_m: number;
            /**
             * Share
             * @description Udział w długości całej sieci pieszej
             */
            share: number;
        };
        /**
         * DataGapsSummary
         * @description Gdzie brakuje danych o dostępności - argument dla miasta (np. do inwentaryzacji).
         */
        DataGapsSummary: {
            /**
             * Max Confidence
             * @description Odcinek z pewnością <= tej wartości to 'brak danych'
             */
            max_confidence: number;
            /**
             * Total Length M
             * @description Długość całej sieci pieszej w obszarze
             */
            total_length_m: number;
            /** Gap Length M */
            gap_length_m: number;
            /** Gap Share */
            gap_share: number;
            /** Gap Segments */
            gap_segments: number;
            /**
             * No Surface M
             * @description W tym bez danych o nawierzchni
             */
            no_surface_m: number;
            /**
             * Imprecise Incline M
             * @description W tym z nachyleniem oznaczonym w OSM bez wartości
             */
            imprecise_incline_m: number;
            /** By Kind */
            by_kind: components["schemas"]["GapKind"][];
            /**
             * Areas
             * @description Obszary z największą długością braków
             */
            areas: components["schemas"]["GapArea"][];
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "easy" | "moderate" | "hard";
        /**
         * GapArea
         * @description Kwadrat ok. 200 x 200 m z odcinkami bez wiarygodnych danych.
         */
        GapArea: {
            /**
             * Label
             * @description Np. 'okolice: Karmelicka' - najdłuższa nazwana ulica w kwadracie
             */
            label: string;
            center: components["schemas"]["LatLon"];
            /** Gap Length M */
            gap_length_m: number;
            /** Segments */
            segments: number;
        };
        /** GapKind */
        GapKind: {
            /**
             * Highway
             * @description Rodzaj drogi z OSM, np. 'footway'
             */
            highway: string | null;
            /**
             * Label
             * @description Po polsku, np. 'chodnik'
             */
            label: string;
            /** Gap Length M */
            gap_length_m: number;
        };
        /**
         * GeocodeResult
         * @description Podpowiedź wyszukiwarki adresów - ten sam kształt co punkt A/B na froncie.
         */
        GeocodeResult: {
            /**
             * Label
             * @description Nazwa do wyświetlenia, np. 'Sukiennice' albo 'Grodzka 20'
             */
            label: string;
            /**
             * Description
             * @description Kontekst: adres i dzielnica, np. 'Rynek Główny 3 · Stare Miasto'
             */
            description?: string | null;
            /**
             * Kind
             * @description Rodzaj obiektu po polsku, np. 'ulica'
             */
            kind?: string | null;
            point: components["schemas"]["LatLon"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * Institution
         * @description Instytucja publiczna z deklaracji dostępności (BIP).
         */
        Institution: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /**
             * Kind
             * @description Rodzaj po polsku, np. 'urząd', 'muzeum', 'teatr'
             */
            kind: string;
            location?: components["schemas"]["InstitutionLocation"] | null;
            /** Attributes */
            attributes?: components["schemas"]["InstitutionAttribute"][];
        };
        /** InstitutionAttribute */
        InstitutionAttribute: {
            /**
             * Category
             * @description Klucz z danych źródłowych, np. 'winda', 'toaleta'
             */
            category: string;
            /**
             * Label
             * @description Nazwa po polsku do wyświetlenia, np. 'Winda'
             */
            label: string;
            /**
             * Value
             * @description Opis z deklaracji; null = brak informacji
             */
            value: string | null;
            /** Source */
            source: string;
            /** Last Verified */
            last_verified?: string | null;
            /** Confidence */
            confidence: number;
            status: components["schemas"]["InstitutionDataStatus"];
            /** Note */
            note?: string | null;
        };
        /**
         * InstitutionDataStatus
         * @enum {string}
         */
        InstitutionDataStatus: "confirmed" | "confirmed_no_date" | "unknown";
        /** InstitutionLocation */
        InstitutionLocation: {
            point: components["schemas"]["LatLon"];
            /**
             * Source
             * @description Skąd współrzędne, np. geokoder Photon (OSM)
             */
            source: string;
            /**
             * Exact
             * @description False = punkt tylko na ulicy, bez numeru domu
             */
            exact: boolean;
        };
        /** LatLon */
        LatLon: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * LayerId
         * @description Warstwy mapy (chipy). Kolejność = kolejność chipów.
         * @enum {string}
         */
        LayerId: "barriers" | "health" | "institutions" | "places" | "reports" | "rest" | "parking" | "events" | "gaps";
        /** LineStringGeometry */
        LineStringGeometry: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /**
             * Coordinates
             * @description Punkty [lon, lat] (RFC 7946)
             */
            coordinates: [
                number,
                number
            ][];
        };
        /**
         * ModeId
         * @description Tryb wybierany na ekranie startowym (docs/plan-frontend-claude.md §4).
         * @enum {string}
         */
        ModeId: "wheelchair" | "senior" | "tourist" | "stroller" | "guest";
        /** ModePreset */
        ModePreset: {
            id: components["schemas"]["ModeId"];
            /**
             * Label
             * @description Potrzeba, nie diagnoza, np. 'Poruszam się na wózku'
             */
            label: string;
            /** Description */
            description: string;
            /**
             * Icon
             * @description Emoji ikony trybu
             */
            icon: string;
            /**
             * Profile
             * @description Profil routingu, np. 'walk' (klucz w routing/profiles.py)
             */
            profile: string;
            /** @description Domyślne preferencje trasy dla trybu */
            preferences: components["schemas"]["RoutePreferences"];
            /**
             * Layers
             * @description Które warstwy mapy są domyślnie włączone
             */
            layers: {
                [key: string]: boolean;
            };
        };
        /** Place */
        Place: {
            /**
             * Id
             * @description Stabilne ID, np. 'osm:node/123'
             */
            id: string;
            /** City */
            city: string;
            /** Name */
            name?: string | null;
            /**
             * Category
             * @description np. 'cafe', 'pharmacy', 'tram_stop'
             */
            category?: string | null;
            location: components["schemas"]["LatLon"];
            /** Attributes */
            attributes?: components["schemas"]["AccessibilityAttribute"][];
        };
        /**
         * Poi
         * @description Punkt dla warstw mapy (odpoczynek, przewijaki). Kształt jak `DemoPoi` we froncie.
         */
        Poi: {
            /**
             * Id
             * @description Np. 'osm:node/123'
             */
            id: string;
            kind: components["schemas"]["PoiKind"];
            /** Name */
            name?: string | null;
            location: components["schemas"]["LatLon"];
            /**
             * Details
             * @description Szczegóły z OSM, np. ławka: backrest, armrest, seats, material; przewijak: place_type, location, fee, wheelchair, opening_hours
             */
            details?: {
                [key: string]: string | number | boolean;
            };
            /**
             * Source
             * @description Źródło danych, np. 'osm'
             */
            source: string;
            provenance: components["schemas"]["Provenance"];
            /** Confidence */
            confidence: number;
        };
        /**
         * PoiKind
         * @enum {string}
         */
        PoiKind: "bench" | "changing_table";
        /**
         * PriorityStreet
         * @description Ulica do naprawy w pierwszej kolejności - argument dla miasta (B2G).
         */
        PriorityStreet: {
            /** Street */
            street: string;
            /**
             * Score
             * @description Suma wag barier (patrz `priority_weights`)
             */
            score: number;
            /** Barriers */
            barriers: number;
            /** By Type */
            by_type: {
                [key: string]: number;
            };
        };
        /** Provenance */
        Provenance: {
            /**
             * Source
             * @description Nazwa providera, np. 'osm', 'msip'
             */
            source: string;
            source_type: components["schemas"]["SourceType"];
            /**
             * Source Ref
             * @description ID/URL rekordu w źródle, np. 'node/123456'
             */
            source_ref?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Last Verified
             * @description Kiedy informacja była ostatnio potwierdzona w źródle
             */
            last_verified?: string | null;
        };
        /** ProviderConfig */
        ProviderConfig: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** Report */
        Report: {
            /** @default barrier */
            type: components["schemas"]["ReportType"];
            location: components["schemas"]["LatLon"];
            /** Place Id */
            place_id?: string | null;
            /** @description Wymagane dla typu 'barrier'; dla innych typów domyślne */
            attribute?: components["schemas"]["AttributeKey"] | null;
            /** Value */
            value?: boolean | number | string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Valid Until
             * @description Przewidywany koniec utrudnienia (np. remontu), jeśli znany
             */
            valid_until?: string | null;
            /** Id */
            id: string;
            /** City */
            city: string;
            /** @default pending */
            status: components["schemas"]["ReportStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Confirmations
             * @description Głosy „Potwierdzam” innych osób
             * @default 0
             */
            confirmations: number;
            /**
             * Denials
             * @description Głosy „Problemu już nie ma”
             * @default 0
             */
            denials: number;
            /**
             * Last Confirmed At
             * @description Ostatnie „Potwierdzam” - od niego liczy się ważność (#63)
             */
            last_confirmed_at?: string | null;
        };
        /**
         * ReportCreate
         * @description Zgłoszenie użytkownika. Celowo bez danych osobowych (patrz docs/security-privacy.md).
         */
        ReportCreate: {
            /** @default barrier */
            type: components["schemas"]["ReportType"];
            location: components["schemas"]["LatLon"];
            /** Place Id */
            place_id?: string | null;
            /** @description Wymagane dla typu 'barrier'; dla innych typów domyślne */
            attribute?: components["schemas"]["AttributeKey"] | null;
            /** Value */
            value?: boolean | number | string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Valid Until
             * @description Przewidywany koniec utrudnienia (np. remontu), jeśli znany
             */
            valid_until?: string | null;
            /**
             * Reporter
             * @description Losowy identyfikator urządzenia - autor nie może potwierdzić własnego zgłoszenia. Bez danych osobowych.
             */
            reporter?: string | null;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "pending" | "confirmed" | "rejected" | "resolved";
        /** ReportStatusCount */
        ReportStatusCount: {
            status: components["schemas"]["ReportStatus"];
            /** Count */
            count: number;
        };
        /**
         * ReportType
         * @enum {string}
         */
        ReportType: "barrier" | "elevator_broken" | "construction" | "inaccessible_entrance" | "blocked_parking";
        /** ReportTypeCount */
        ReportTypeCount: {
            type: components["schemas"]["ReportType"];
            /** Count */
            count: number;
        };
        /**
         * ReportUpdate
         * @description Zmiana statusu przez moderację (na razie bez logowania - patrz #37).
         */
        ReportUpdate: {
            status: components["schemas"]["ReportStatus"];
        };
        /**
         * ReportVote
         * @description Głos innej osoby: potwierdza zgłoszenie albo mówi, że problemu już nie ma.
         */
        ReportVote: {
            vote: components["schemas"]["VoteKind"];
            /**
             * Voter
             * @description Losowy identyfikator urządzenia
             */
            voter: string;
        };
        /**
         * RouteAlternative
         * @description Pełna alternatywa trasy, gotowa do pokazania obok trasy głównej.
         */
        RouteAlternative: {
            /** Label */
            label: string;
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Stairs Count */
            stairs_count: number;
            /** Rough Surface M */
            rough_surface_m: number;
            /** Geometry */
            geometry: components["schemas"]["LatLon"][];
            /** Segments */
            segments: components["schemas"]["RouteSegment"][];
            /** Explanation */
            explanation: string;
        };
        /**
         * RouteBarrier
         * @description Bariera na odcinku trasy - do podsumowania „na tej trasie: …”.
         */
        RouteBarrier: {
            type: components["schemas"]["BarrierType"];
            /**
             * Description
             * @description Np. 'Krawężnik ok. 10 cm'
             */
            description: string;
        };
        /**
         * RouteBaseline
         * @description Najkrótsza zwykła trasa piesza - do porównania, czego unikamy.
         */
        RouteBaseline: {
            /** Distance M */
            distance_m: number;
            /** Stairs Count */
            stairs_count: number;
            /** Rough Surface M */
            rough_surface_m: number;
            /** Geometry */
            geometry: components["schemas"]["LatLon"][];
        };
        /**
         * RoutePreferences
         * @description Preferencje trasy. Pytamy o potrzeby, NIE o niepełnosprawność.
         */
        RoutePreferences: {
            /**
             * Avoid Stairs
             * @default true
             */
            avoid_stairs: boolean;
            /**
             * Max Incline Percent
             * @default 6
             */
            max_incline_percent: number;
            /**
             * Max Kerb Height Cm
             * @default 3
             */
            max_kerb_height_cm: number;
            /**
             * Avoid Rough Surface
             * @default true
             */
            avoid_rough_surface: boolean;
            /**
             * Prefer Lit Paths
             * @default false
             */
            prefer_lit_paths: boolean;
            /**
             * Profile
             * @description Profil routingu: 'wheelchair', 'stroller', 'senior' albo 'walk'; brak lub nieznany = 'walk'. Presety trybów: GET /api/profiles
             */
            profile?: string | null;
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * City
             * @default krakow
             */
            city: string;
            origin: components["schemas"]["LatLon"];
            destination: components["schemas"]["LatLon"];
            preferences?: components["schemas"]["RoutePreferences"];
        };
        /** RouteResponse */
        RouteResponse: {
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Segments */
            segments: components["schemas"]["RouteSegment"][];
            /**
             * Accessibility Score
             * @description Wynik dostępności całej trasy, ważony długością jej odcinków
             */
            accessibility_score: number;
            /**
             * Confidence
             * @description Pewność danych całej trasy, ważona długością jej odcinków
             */
            confidence: number;
            /** Warnings */
            warnings?: string[];
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Profile */
            profile?: string | null;
            /** Rough Surface M */
            rough_surface_m?: number | null;
            /** Stairs Count */
            stairs_count?: number | null;
            baseline?: components["schemas"]["RouteBaseline"] | null;
            /** Explanation */
            explanation: string;
            /** Alternatives */
            alternatives?: components["schemas"]["RouteAlternative"][];
            /**
             * Reports Considered
             * @description Aktywne zgłoszenia uwzględnione przy liczeniu - nowe poza tą listą oznaczają, że trasę warto przeliczyć (#63)
             */
            reports_considered?: string[];
        };
        /**
         * RouteSegment
         * @description Odcinek trasy z opisem tekstowym - to jest tekstowa alternatywa mapy (WCAG).
         */
        RouteSegment: {
            /**
             * Instruction
             * @description Np. 'Skręć w prawo w ul. Floriańską'
             */
            instruction: string;
            /** Distance M */
            distance_m: number;
            /** Geometry */
            geometry: components["schemas"]["LatLon"][];
            /**
             * Street
             * @description Nazwa ulicy lub rodzaj drogi
             */
            street?: string | null;
            /** Surface */
            surface?: string | null;
            /** Incline Percent */
            incline_percent?: number | null;
            /** Warnings */
            warnings?: string[];
            /** @default easy */
            difficulty: components["schemas"]["Difficulty"];
            /**
             * Accessibility Score
             * @description Dostępność odcinka dla wybranego profilu: 0 = niedostępny, 100 = bez barier i kar routingu
             */
            accessibility_score: number;
            /** @default unverified */
            data_status: components["schemas"]["AttributeStatus"];
            /**
             * Confidence
             * @description Pewność danych odcinka: 0 = brak wiarygodnych danych, 1 = pełna pewność
             */
            confidence: number;
            /**
             * Sources
             * @description Źródła danych odcinka
             */
            sources?: string[];
            /**
             * Fetched At
             * @description Kiedy dane odcinka pobrano ze źródła (np. z OSM)
             */
            fetched_at?: string | null;
            /**
             * Last Verified
             * @description Najstarsza data weryfikacji w terenie (OSM check_date); brak = brak
             */
            last_verified?: string | null;
            /**
             * Barriers
             * @description Bariery na odcinku (schody, krawężnik, bruk…)
             */
            barriers?: components["schemas"]["RouteBarrier"][];
        };
        /** RoutingConfig */
        RoutingConfig: {
            /**
             * Network Type
             * @default walk
             */
            network_type: string;
            /** Overpass Url */
            overpass_url?: string | null;
        };
        /**
         * SearchResult
         * @description Wynik wyszukiwarki miejsc. Pola label/description/kind/point jak w GeocodeResult.
         */
        SearchResult: {
            /**
             * Id
             * @description Stabilne ID wyniku, np. 'institution:mk-krzysztofory'
             */
            id: string;
            source: components["schemas"]["SearchResultKind"];
            /**
             * Label
             * @description Nazwa do wyświetlenia
             */
            label: string;
            /**
             * Description
             * @description Adres albo kontekst
             */
            description?: string | null;
            /**
             * Kind
             * @description Rodzaj po polsku, np. 'apteka', 'muzeum'
             */
            kind?: string | null;
            point: components["schemas"]["LatLon"];
            /**
             * Institution Id
             * @description Dla source=institution
             */
            institution_id?: string | null;
            /** @description Dla source=place: miejsce z atrybutami */
            place?: components["schemas"]["Place"] | null;
            /**
             * Match
             * @description 'category' = zapytanie o rodzaj/cechę (np. 'hotel', 'przewijak') - zwracamy WSZYSTKIE takie miejsca w obszarze, a nie kilka najlepszych dopasowań
             * @default name
             * @enum {string}
             */
            match: "name" | "category";
            /**
             * Distance M
             * @description Odległość od punktu `lat`/`lon` z zapytania (np. środka mapy)
             */
            distance_m?: number | null;
        };
        /**
         * SearchResultKind
         * @enum {string}
         */
        SearchResultKind: "institution" | "place" | "address";
        /**
         * SegmentCollection
         * @description Odcinki sieci pieszej jako GeoJSON - do podania wprost do źródła `geojson` w MapLibre.
         */
        SegmentCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["SegmentFeature"][];
            /**
             * Truncated
             * @description True, gdy w bbox jest więcej odcinków niż limit
             * @default false
             */
            truncated: boolean;
        };
        /** SegmentFeature */
        SegmentFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["LineStringGeometry"];
            properties: components["schemas"]["SegmentProperties"];
        };
        /** SegmentProperties */
        SegmentProperties: {
            /**
             * Id
             * @description '{u}-{v}-{key}' - krawędź grafu OSM
             */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Highway
             * @description Rodzaj drogi z OSM, np. 'footway'
             */
            highway?: string | null;
            /** Osm Way Id */
            osm_way_id?: number | null;
            /** Length M */
            length_m: number;
            difficulty: components["schemas"]["Difficulty"];
            /**
             * Confidence
             * @description Pewność danych odcinka - ta sama reguła co w opisie trasy
             */
            confidence: number;
            /** Attributes */
            attributes?: components["schemas"]["AccessibilityAttribute"][];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "osm" | "open_data" | "msip" | "user_report" | "manual";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoteKind
         * @enum {string}
         */
        VoteKind: "confirm" | "deny";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_cities_api_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityConfig"][];
                };
            };
        };
    };
    list_places_api_places_get: {
        parameters: {
            query?: {
                city?: string;
                /** @description Szukaj po nazwie */
                q?: string | null;
                /** @description Obszar 'south,west,north,east' (WGS84). Domyślnie obszar demo miasta. */
                bbox?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pois_api_pois_get: {
        parameters: {
            query?: {
                city?: string;
                /** @description bench (ławki) i/lub changing_table (przewijaki); brak = oba */
                kind?: components["schemas"]["PoiKind"][] | null;
                /** @description Obszar 'south,west,north,east' (WGS84). Domyślnie obszar demo miasta. */
                bbox?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Poi"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModePreset"][];
                };
            };
        };
    };
    plan_api_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_geojson_api_routes_geojson_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: {
                city?: string;
                status?: components["schemas"]["ReportStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_reports_post: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_reports_api_reports_active_get: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveReport"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_on_report_api_reports__report_id__votes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportVote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_report_api_reports__report_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_api_geocode_get: {
        parameters: {
            query: {
                /** @description Adres, ulica albo nazwa miejsca */
                q: string;
                city?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_geocode_api_geocode_reverse_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_institutions_api_institutions_get: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Institution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                /** @description Nazwa miejsca, rodzaj (np. 'apteka') albo adres */
                q: string;
                city?: string;
                limit?: number;
                /** @description Np. środek widoku mapy */
                lat?: number | null;
                lon?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_api_segments_get: {
        parameters: {
            query: {
                /** @description Obszar 's,w,n,e' (WGS84), obowiązkowy */
                bbox: string;
                city?: string;
                /** @description Tylko odcinki z pewnością danych <= tej wartości */
                max_confidence?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_gaps_api_data_gaps_get: {
        parameters: {
            query?: {
                city?: string;
                /** @description Obszar 's,w,n,e' (WGS84). Domyślnie obszar demo miasta. */
                bbox?: string | null;
                /** @description Odcinek z pewnością <= tej wartości to brak danych (0.4 = brak nawierzchni) */
                max_confidence?: number;
                /** @description Ile obszarów z największymi brakami */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataGapsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_barriers_api_barriers_get: {
        parameters: {
            query: {
                /** @description Obszar 's,w,n,e' (WGS84), obowiązkowy */
                bbox: string;
                city?: string;
                /** @description Tylko te typy, np. ?types=stairs&types=kerb */
                types?: components["schemas"]["BarrierType"][] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarrierList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    city_stats_api_stats_get: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
