/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Places */
        get: operations["list_places_api_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_api_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessibilityAttribute */
        AccessibilityAttribute: {
            key: components["schemas"]["AttributeKey"];
            /** Value */
            value: boolean | number | string;
            provenance: components["schemas"]["Provenance"];
            /**
             * Confidence
             * @description 0 = nie wiemy, 1 = pewne
             */
            confidence: number;
            /** @default unverified */
            status: components["schemas"]["AttributeStatus"];
            /** Alternatives */
            alternatives?: components["schemas"]["AccessibilityAttribute"][];
        };
        /**
         * AttributeKey
         * @description Słownik cech dostępności. Dodajemy nowe klucze tutaj, nie ad hoc w kodzie.
         * @enum {string}
         */
        AttributeKey: "wheelchair" | "step_free_entrance" | "stairs" | "step_count" | "ramp" | "elevator" | "accessible_toilet" | "surface" | "incline_percent" | "kerb_height_cm" | "width_cm" | "tactile_paving";
        /**
         * AttributeStatus
         * @enum {string}
         */
        AttributeStatus: "verified" | "unverified" | "conflicting" | "outdated";
        /** CityConfig */
        CityConfig: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Timezone */
            timezone: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Demo Bbox */
            demo_bbox?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Center */
            center: [
                number,
                number
            ];
            /**
             * Default Zoom
             * @default 13
             */
            default_zoom: number;
            /** Providers */
            providers?: components["schemas"]["ProviderConfig"][];
            routing?: components["schemas"]["RoutingConfig"];
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "easy" | "moderate" | "hard";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** LatLon */
        LatLon: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** Place */
        Place: {
            /**
             * Id
             * @description Stabilne ID, np. 'osm:node/123'
             */
            id: string;
            /** City */
            city: string;
            /** Name */
            name?: string | null;
            /**
             * Category
             * @description np. 'cafe', 'pharmacy', 'tram_stop'
             */
            category?: string | null;
            location: components["schemas"]["LatLon"];
            /** Attributes */
            attributes?: components["schemas"]["AccessibilityAttribute"][];
        };
        /** Provenance */
        Provenance: {
            /**
             * Source
             * @description Nazwa providera, np. 'osm', 'msip'
             */
            source: string;
            source_type: components["schemas"]["SourceType"];
            /**
             * Source Ref
             * @description ID/URL rekordu w źródle, np. 'node/123456'
             */
            source_ref?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Last Verified
             * @description Kiedy informacja była ostatnio potwierdzona w źródle
             */
            last_verified?: string | null;
        };
        /** ProviderConfig */
        ProviderConfig: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** Report */
        Report: {
            location: components["schemas"]["LatLon"];
            /** Place Id */
            place_id?: string | null;
            attribute: components["schemas"]["AttributeKey"];
            /** Value */
            value: boolean | number | string;
            /** Comment */
            comment?: string | null;
            /** Id */
            id: string;
            /** City */
            city: string;
            /** @default pending */
            status: components["schemas"]["ReportStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportCreate
         * @description Zgłoszenie użytkownika. Celowo bez danych osobowych (patrz docs/security-privacy.md).
         */
        ReportCreate: {
            location: components["schemas"]["LatLon"];
            /** Place Id */
            place_id?: string | null;
            attribute: components["schemas"]["AttributeKey"];
            /** Value */
            value: boolean | number | string;
            /** Comment */
            comment?: string | null;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "pending" | "confirmed" | "rejected" | "resolved";
        /**
         * RouteBaseline
         * @description Najkrótsza zwykła trasa piesza - do porównania, czego unikamy.
         */
        RouteBaseline: {
            /** Distance M */
            distance_m: number;
            /** Stairs Count */
            stairs_count: number;
            /** Rough Surface M */
            rough_surface_m: number;
            /** Geometry */
            geometry: components["schemas"]["LatLon"][];
        };
        /**
         * RoutePreferences
         * @description Preferencje trasy. Pytamy o potrzeby, NIE o niepełnosprawność.
         */
        RoutePreferences: {
            /**
             * Avoid Stairs
             * @default true
             */
            avoid_stairs: boolean;
            /**
             * Max Incline Percent
             * @default 6
             */
            max_incline_percent: number;
            /**
             * Max Kerb Height Cm
             * @default 3
             */
            max_kerb_height_cm: number;
            /**
             * Avoid Rough Surface
             * @default true
             */
            avoid_rough_surface: boolean;
            /**
             * Prefer Lit Paths
             * @default false
             */
            prefer_lit_paths: boolean;
            /**
             * Profile
             * @description Gotowy preset: 'wheelchair' lub 'stroller' (opcjonalnie)
             */
            profile?: string | null;
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * City
             * @default krakow
             */
            city: string;
            origin: components["schemas"]["LatLon"];
            destination: components["schemas"]["LatLon"];
            preferences?: components["schemas"]["RoutePreferences"];
        };
        /** RouteResponse */
        RouteResponse: {
            /** Distance M */
            distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Segments */
            segments: components["schemas"]["RouteSegment"][];
            /** Warnings */
            warnings?: string[];
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Profile */
            profile?: string | null;
            /** Rough Surface M */
            rough_surface_m?: number | null;
            /** Stairs Count */
            stairs_count?: number | null;
            baseline?: components["schemas"]["RouteBaseline"] | null;
        };
        /**
         * RouteSegment
         * @description Odcinek trasy z opisem tekstowym - to jest tekstowa alternatywa mapy (WCAG).
         */
        RouteSegment: {
            /**
             * Instruction
             * @description Np. 'Skręć w prawo w ul. Floriańską'
             */
            instruction: string;
            /** Distance M */
            distance_m: number;
            /** Geometry */
            geometry: components["schemas"]["LatLon"][];
            /**
             * Street
             * @description Nazwa ulicy lub rodzaj drogi
             */
            street?: string | null;
            /** Surface */
            surface?: string | null;
            /** Incline Percent */
            incline_percent?: number | null;
            /** Warnings */
            warnings?: string[];
            /** @default easy */
            difficulty: components["schemas"]["Difficulty"];
            /** @default unverified */
            data_status: components["schemas"]["AttributeStatus"];
            /** Confidence */
            confidence: number;
            /**
             * Sources
             * @description Źródła danych odcinka
             */
            sources?: string[];
        };
        /** RoutingConfig */
        RoutingConfig: {
            /**
             * Network Type
             * @default walk
             */
            network_type: string;
            /** Overpass Url */
            overpass_url?: string | null;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "osm" | "open_data" | "msip" | "user_report" | "manual";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_cities_api_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityConfig"][];
                };
            };
        };
    };
    list_places_api_places_get: {
        parameters: {
            query?: {
                city?: string;
                /** @description Szukaj po nazwie */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_reports_post: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
